:toc:
:sectnums:
:toclevels: 5
:sectnumlevels: 5
:showcomments:
:xrefstyle: short
:icons: font
:source-highlighter: coderay
:tick: &#x2714;
:pound: &#xA3;

= New CSProj format

There is a new and far leaner format for C# .csproj files which is often referred to as _SDK format_. The projects
are called _SDK projects_. You can change to the new format quite easily and this involves no code changes.

The easiest and perhaps best way to convert from the old `.csproj` format to the new one is to simply completely 
replace the content as follows:

----
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
</Project>
----

== Output Path

The default output path for projects has changed. By default, this contains the .Net Framework name 
as the last component of the path. For example:

----
r:\proggen-all\proggen-newproj\proggen\bin\debug\net472
----

In order to change this back to the "old" output path, we can add the following to the `.csproj` file:

----
<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
----

== Solution File

The format of the solution file has not changed, however, the _Project Type GUID_ for new projects is 
different:

Replace 


----
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "MyProject", "MyProject\MyProject.csproj", "{03466056-3460-4B9C-A4DF-F8051DC8238E}"
----

with

----
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "MyProject", "MyProject\MyProject.csproj", "{03466056-3460-4B9C-A4DF-F8051DC8238E}"
----


== AssemblyInfo.cs

By default, this file is no longer included in new projects and if you do convert a project to the new
format and do not delete `AssemblyInfo.cs`, you will see conflicts.

In order to allow properties to be defined in AssemblyInfo.cs, add one or more
of the following attributes to the `.csproj` file:

----
<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
<GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
<GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
<GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
<GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
<GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
<GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
<GenerateNeutralResourcesLanguageAttribute>false</GenerateNeutralResourcesLanguageAttribute>
----

== Directory.build.props

Directory.build.props is picked up by MS Build etc. You can place it in the root of your repo and 
it will be used for all projects.

----
<Project>
    <PropertyGroup>
        <Company>Blah Blah things</Company>
        <Copyright>Copyright © 2020</Copyright>
        <AssemblyVersion>2.7.1.8</AssemblyVersion>
        <FileVersion>5.9.2.6</FileVersion>
        <Version>3.1.4.1</Version>
    </PropertyGroup>
</Project>
----

=== Copyright symbol

In order to see the copyright symbol correctly in the explorer Properties dialog box, you need to 
make sure it is encoded as UTF-8


=== Product Version

In order to get the copyright symbol into the explorer Properties dialog box, you need to set
the AssemblyInformationalVersionAttribute
